//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassInfo
    {
        public int ClassId { get; set; }
        public string ClassName { get; set; }
        public string AddTime { get; set; }
        public Nullable<bool> DelFlag { get; set; }
        public string ReMark { get; set; }
        public string LastTime { get; set; }
    }
}
