//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentInfo
    {
        public int StuId { get; set; } = 0;
        public string Sex { get; set; }
        public Nullable<int> Age { get; set; }
        public int ClassId { get; set; }
        public string LoginName { get; set; }
        public string NicKName { get; set; }
        public string AddTime { get; set; }
        public Nullable<bool> DelFlag { get; set; }
        public string Remark { get; set; }
        public string LastTime { get; set; }
    }
}
