//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Runtime.Remoting.Metadata.W3cXsd2001;

    public partial class StudentEntities : DbContext
    {
        private StudentEntities studentEntities;

        public StudentEntities()
            : base("name=StudentEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClassInfo> ClassInfo { get; set; }
        public virtual DbSet<StudentInfo> StudentInfo { get; set; }
        public virtual DbSet<TeacherInfo> TeacherInfo { get; set; }

        public static implicit operator StudentEntities(SoapEntities v)
        {
            throw new NotImplementedException();
        }
    }
}
