//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherInfo
    {
        public int ID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public string TeacherName { get; set; }
        public string Addtime { get; set; }
        public string TeacherPW { get; set; }
        public Nullable<bool> DelFlage { get; set; }
        public string ReMark { get; set; }
    }
}
