//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StuManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class TStudent
    {
        public int StuId { get; set; }
        public int ClassId { get; set; }
        public string StuName { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> DelFlag { get; set; }
        public string Remark { get; set; }
    }
}
